version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.1.4
    environment:
      RB_SYS_FORCE_INSTALL_RUST_TOOLCHAIN: 'true'
    steps:
      - checkout
      - run:
          name: Install Rust/Cargo dependencies
          command: apt-get update && apt-get install -y clang
      - run:
          name: Install a RubyGems version that can compile rust extensions
          command: gem update --system '3.3.26'
      - run:
          name: Run the default task
          command: |
            gem install bundler -v 2.5.23
            bundle install
            bundle exec rake
